name: Asana integration after Pull Request submitted

on:
    pull_request:
      types: [opened, reopened]
  
jobs:
    add-task-to-app-board:
      runs-on: ubuntu-latest
      steps:
        - name: Add Asana task to Project
          uses: duckduckgo/native-github-asana-sync@v1.0
          with:
            asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
            trigger-phrase: 'ASANA TASK:'
            asana-project: '414235014887631'
            asana-section: '414413334607374'
            action: 'add-task-asana-project'