on:
    pull_request:
      types: [opened, reopened]
  
jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
        - name: Add Asana task to Project
          uses: duckduckgo/native-github-asana-sync@v1.0
          with:
            trigger-phrase: 'Task/Issue URL:'
            asana-project: '414235014887631'
            asana-section: '414413334607374'
            action: 'add-task-asana-project'